# Generated by Django 2.2.5 on 2020-02-01 02:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedBookID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=30)),
                ('book_title', models.CharField(max_length=100)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('page_count', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('username', 'book_id')},
            },
        ),
    ]
